# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ingredients',
        ),
    ]
