# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/img/recipes'),
        ),
    ]
