# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 19:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171218_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='difficulty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='post',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
    ]
