# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20171218_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
