# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cookingtime',
            field=models.CharField(default=0, help_text='Please enter time in minutes', max_length=3),
        ),
    ]
