# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20171219_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='post',
            name='minutes',
        ),
    ]
