# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 22:12
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='post_image'),
        ),
    ]
