# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20171220_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='qty',
        ),
    ]
