# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 22:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_post_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='qty',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
