# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20171221_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
