# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 05:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0025_auto_20171221_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
