# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_comment_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(help_text='Short summary for All recipes page', max_length=150, null=True),
        ),
    ]
