# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20171222_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='seen',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='post',
            name='voted',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
