# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20171222_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=10)),
                ('measurement', models.CharField(blank=True, choices=[('tbsp', 'tbsp'), ('tsp', 'tsp'), ('g', 'g'), ('kg', 'kg'), ('tsp', 'tsp'), ('ml', 'ml'), ('l', 'l')], max_length=200, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='blog.Post')),
            ],
        ),
    ]
