# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
