# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0030_auto_20180111_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('5', ''), ('4 and a half', ''), ('4', ''), ('3 and a half', ''), ('2 and a half', ''), ('2', ''), ('1 and a half', ''), ('1', '')], max_length=100)),
                ('author_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='stars',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='voted',
            new_name='votes',
        ),
        migrations.AddField(
            model_name='rate',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='blog.Post'),
        ),
    ]
