# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 22:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0031_auto_20180114_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('3.5', '3 and a half'), ('2', '2'), ('1', '1'), ('5', 'Awesome'), ('2.5', '2 and a half'), ('1.5', '1 and a half'), ('4', '4'), ('3', '3'), ('4.5', '4 and a half')], default='5', max_length=100)),
                ('author_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='rate',
            name='author_user',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='stars',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=2),
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
        migrations.AddField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='blog.Post'),
        ),
    ]
