# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_remove_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement',
            field=models.CharField(blank=True, choices=[('tbsp', 'tbsp'), ('tsp', 'tsp'), ('g', 'g'), ('kg', 'kg'), ('tsp', 'tsp'), ('ml', 'ml'), ('piece', 'piece'), ('l', 'l')], max_length=200, null=True),
        ),
    ]
