# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 15:30
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20180114_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='post_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='post_image'),
        ),
    ]
