# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20180114_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='step_number',
        ),
    ]
