# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20180114_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.CharField(choices=[('Milk', 'Milk'), ('Tree nut', 'Tree nut'), ('Egg', 'Egg'), ('Wheat', 'Wheat'), ('Gluten', 'Gluten'), ('Peanut', 'Peanut'), ('Soy', 'Soy'), ('Sesame', 'Sesame'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
