# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_userprofile_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vegetariantype',
            field=models.CharField(choices=[('Vegan', 'Vegan'), ('Lacto Vegetarian', 'Lacto Vegetarian'), ('Ovo Vegetarian', 'Ovo Vegetarian'), ('Lacto-ovo vegetarian', 'Lacto-ovo vegetarian')], max_length=200, null=True),
        ),
    ]
