# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_step_step_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
