# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_post_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='instructions',
        ),
    ]
