# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20180115_0024'),
        ('blog', '0030_auto_20180111_1131'),
    ]

    operations = [
    ]
