# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20180114_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cookingtime',
            field=models.CharField(default=0, help_text='Please enter time in minutes', max_length=3, verbose_name='Cooking Time'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthDate',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='post_image', verbose_name='Profile Picture'),
        ),
    ]
