# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20180114_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], help_text='This information is needed to calculate your daily calorie intake', max_length=100, null=True),
        ),
    ]
