# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthDate',
            field=models.DateField(blank=True, help_text='Please use the following format: year-month-day', null=True, verbose_name='Date Of Birth'),
        ),
    ]
