# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20180115_1131'),
        ('blog', '0038_merge_20180115_1139'),
        ('blog', '0033_auto_20180115_1110'),
    ]

    operations = [
    ]
