# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_follower_current_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='Friend',
        ),
    ]
